// Language translations
const translations = {
    en: {
        // Common
        dashboard: "Dashboard",
        reports: "Reports",
        alerts: "Alerts",
        profile: "Profile",
        settings: "Settings",
        logout: "Logout",
        loading: "Loading...",
        error: "Error",
        success: "Success",
        cancel: "Cancel",
        save: "Save",
        delete: "Delete",
        edit: "Edit",
        view: "View",
        search: "Search",
        filter: "Filter",
        clear: "Clear",
        apply: "Apply",
        close: "Close",
        confirm: "Confirm",
        warning: "Warning",
        info: "Information",
        yes: "Yes",
        no: "No",
        ok: "OK",
        back: "Back",
        next: "Next",
        previous: "Previous",
        first: "First",
        last: "Last",
        page: "Page",
        of: "of",
        items: "items",
        perPage: "per page",
        showing: "Showing",
        to: "to",
        results: "results",
        noResults: "No results found",
        loadingData: "Loading data...",
        pleaseWait: "Please wait...",
        processing: "Processing...",
        updating: "Updating...",
        saving: "Saving...",
        deleting: "Deleting...",
        errorOccurred: "An error occurred",
        tryAgain: "Please try again",
        connectionError: "Connection error",
        sessionExpired: "Session expired",
        pleaseLogin: "Please login again",
        unauthorized: "Unauthorized access",
        forbidden: "Access forbidden",
        notFound: "Page not found",
        serverError: "Server error",
        maintenance: "System maintenance",
        comingSoon: "Coming soon",
        underDevelopment: "Under development",
        beta: "Beta",
        version: "Version",
        help: "Help",
        support: "Support",
        feedback: "Feedback",
        contact: "Contact",
        about: "About",
        terms: "Terms",
        privacy: "Privacy",
        cookies: "Cookies",
        copyright: "Copyright",
        allRightsReserved: "All rights reserved",
        poweredBy: "Powered by",
        developedBy: "Developed by",
        designedBy: "Designed by",
        credits: "Credits",
        license: "License",
        documentation: "Documentation",
        api: "API",
        changelog: "Changelog",
        roadmap: "Roadmap",
        features: "Features",
        pricing: "Pricing",
        plans: "Plans",
        subscribe: "Subscribe",
        unsubscribe: "Unsubscribe",
        upgrade: "Upgrade",
        downgrade: "Downgrade",
        trial: "Trial",
        free: "Free",
        paid: "Paid",
        premium: "Premium",
        basic: "Basic",
        standard: "Standard",
        professional: "Professional",
        enterprise: "Enterprise",
        custom: "Custom",
        monthly: "Monthly",
        yearly: "Yearly",
        lifetime: "Lifetime",
        oneTime: "One-time",
        recurring: "Recurring",
        automatic: "Automatic",
        manual: "Manual",
        enabled: "Enabled",
        disabled: "Disabled",
        active: "Active",
        inactive: "Inactive",
        pending: "Pending",
        completed: "Completed",
        failed: "Failed",
        cancelled: "Cancelled",
        expired: "Expired",
        valid: "Valid",
        invalid: "Invalid",
        required: "Required",
        optional: "Optional",
        recommended: "Recommended",
        notRecommended: "Not recommended",
        maximum: "Maximum",
        minimum: "Minimum",
        average: "Average",
        total: "Total",
        count: "Count",
        sum: "Sum",
        percentage: "Percentage",
        ratio: "Ratio",
        rate: "Rate",
        speed: "Speed",
        time: "Time",
        date: "Date",
        duration: "Duration",
        frequency: "Frequency",
        interval: "Interval",
        period: "Period",
        range: "Range",
        limit: "Limit",
        threshold: "Threshold",
        target: "Target",
        goal: "Goal",
        objective: "Objective",
        milestone: "Milestone",
        deadline: "Deadline",
        schedule: "Schedule",
        calendar: "Calendar",
        agenda: "Agenda",
        reminder: "Reminder",
        notification: "Notification",
        alert: "Alert",
        warning: "Warning",
        error: "Error",
        success: "Success",
        info: "Info",
        message: "Message",
        comment: "Comment",
        note: "Note",
        description: "Description",
        details: "Details",
        summary: "Summary",
        overview: "Overview",
        preview: "Preview",
        review: "Review",
        report: "Report",
        analysis: "Analysis",
        statistics: "Statistics",
        metrics: "Metrics",
        data: "Data",
        information: "Information",
        knowledge: "Knowledge",
        wisdom: "Wisdom",
        insight: "Insight",
        perspective: "Perspective",
        view: "View",
        perspective: "Perspective",
        angle: "Angle",
        aspect: "Aspect",
        dimension: "Dimension",
        factor: "Factor",
        element: "Element",
        component: "Component",
        part: "Part",
        piece: "Piece",
        unit: "Unit",
        item: "Item",
        object: "Object",
        subject: "Subject",
        topic: "Topic",
        theme: "Theme",
        category: "Category",
        type: "Type",
        kind: "Kind",
        sort: "Sort",
        order: "Order",
        group: "Group",
        set: "Set",
        collection: "Collection",
        list: "List",
        array: "Array",
        table: "Table",
        chart: "Chart",
        graph: "Graph",
        diagram: "Diagram",
        map: "Map",
        plan: "Plan",
        layout: "Layout",
        design: "Design",
        structure: "Structure",
        format: "Format",
        style: "Style",
        theme: "Theme",
        color: "Color",
        size: "Size",
        shape: "Shape",
        form: "Form",
        pattern: "Pattern",
        texture: "Texture",
        material: "Material",
        quality: "Quality",
        grade: "Grade",
        level: "Level",
        rank: "Rank",
        status: "Status",
        state: "State",
        condition: "Condition",
        situation: "Situation",
        context: "Context",
        environment: "Environment",
        setting: "Setting",
        background: "Background",
        foreground: "Foreground",
        surface: "Surface",
        depth: "Depth",
        height: "Height",
        width: "Width",
        length: "Length",
        area: "Area",
        volume: "Volume",
        weight: "Weight",
        mass: "Mass",
        density: "Density",
        pressure: "Pressure",
        temperature: "Temperature",
        humidity: "Humidity",
        light: "Light",
        sound: "Sound",
        energy: "Energy",
        power: "Power",
        force: "Force",
        motion: "Motion",
        speed: "Speed",
        velocity: "Velocity",
        acceleration: "Acceleration",
        direction: "Direction",
        position: "Position",
        location: "Location",
        place: "Place",
        space: "Space",
        time: "Time",
        date: "Date",
        day: "Day",
        week: "Week",
        month: "Month",
        year: "Year",
        century: "Century",
        era: "Era",
        period: "Period",
        age: "Age",
        generation: "Generation",
        lifetime: "Lifetime",
        duration: "Duration",
        interval: "Interval",
        frequency: "Frequency",
        rate: "Rate",
        speed: "Speed",
        pace: "Pace",
        rhythm: "Rhythm",
        cycle: "Cycle",
        rotation: "Rotation",
        revolution: "Revolution",
        orbit: "Orbit",
        path: "Path",
        route: "Route",
        way: "Way",
        direction: "Direction",
        course: "Course",
        track: "Track",
        trail: "Trail",
        line: "Line",
        curve: "Curve",
        angle: "Angle",
        degree: "Degree",
        radian: "Radian",
        gradient: "Gradient",
        slope: "Slope",
        incline: "Incline",
        decline: "Decline",
        rise: "Rise",
        fall: "Fall",
        increase: "Increase",
        decrease: "Decrease",
        growth: "Growth",
        decline: "Decline",
        progress: "Progress",
        regress: "Regress",
        advance: "Advance",
        retreat: "Retreat",
        forward: "Forward",
        backward: "Backward",
        up: "Up",
        down: "Down",
        left: "Left",
        right: "Right",
        north: "North",
        south: "South",
        east: "East",
        west: "West",
        top: "Top",
        bottom: "Bottom",
        front: "Front",
        back: "Back",
        side: "Side",
        edge: "Edge",
        corner: "Corner",
        center: "Center",
        middle: "Middle",
        half: "Half",
        quarter: "Quarter",
        third: "Third",
        fourth: "Fourth",
        fifth: "Fifth",
        sixth: "Sixth",
        seventh: "Seventh",
        eighth: "Eighth",
        ninth: "Ninth",
        tenth: "Tenth",
        hundredth: "Hundredth",
        thousandth: "Thousandth",
        millionth: "Millionth",
        billionth: "Billionth",
        trillionth: "Trillionth",
        zero: "Zero",
        one: "One",
        two: "Two",
        three: "Three",
        four: "Four",
        five: "Five",
        six: "Six",
        seven: "Seven",
        eight: "Eight",
        nine: "Nine",
        ten: "Ten",
        eleven: "Eleven",
        twelve: "Twelve",
        thirteen: "Thirteen",
        fourteen: "Fourteen",
        fifteen: "Fifteen",
        sixteen: "Sixteen",
        seventeen: "Seventeen",
        eighteen: "Eighteen",
        nineteen: "Nineteen",
        twenty: "Twenty",
        thirty: "Thirty",
        forty: "Forty",
        fifty: "Fifty",
        sixty: "Sixty",
        seventy: "Seventy",
        eighty: "Eighty",
        ninety: "Ninety",
        hundred: "Hundred",
        thousand: "Thousand",
        million: "Million",
        billion: "Billion",
        trillion: "Trillion",
        quadrillion: "Quadrillion",
        quintillion: "Quintillion",
        sextillion: "Sextillion",
        septillion: "Septillion",
        octillion: "Octillion",
        nonillion: "Nonillion",
        decillion: "Decillion",
        undecillion: "Undecillion",
        duodecillion: "Duodecillion",
        tredecillion: "Tredecillion",
        quattuordecillion: "Quattuordecillion",
        quindecillion: "Quindecillion",
        sexdecillion: "Sexdecillion",
        septendecillion: "Septendecillion",
        octodecillion: "Octodecillion",
        novemdecillion: "Novemdecillion",
        vigintillion: "Vigintillion"
    },
    hi: {
        // Common
        dashboard: "डैशबोर्ड",
        reports: "रिपोर्ट्स",
        alerts: "अलर्ट्स",
        profile: "प्रोफाइल",
        settings: "सेटिंग्स",
        logout: "लॉगआउट",
        loading: "लोड हो रहा है...",
        error: "त्रुटि",
        success: "सफल",
        cancel: "रद्द करें",
        save: "सेव करें",
        delete: "हटाएं",
        edit: "संपादित करें",
        view: "देखें",
        search: "खोजें",
        filter: "फ़िल्टर",
        clear: "साफ़ करें",
        apply: "लागू करें",
        close: "बंद करें",
        confirm: "पुष्टि करें",
        warning: "चेतावनी",
        info: "जानकारी",
        yes: "हाँ",
        no: "नहीं",
        ok: "ठीक है",
        back: "वापस",
        next: "अगला",
        previous: "पिछला",
        first: "पहला",
        last: "अंतिम",
        page: "पृष्ठ",
        of: "का",
        items: "आइटम",
        perPage: "प्रति पृष्ठ",
        showing: "दिखा रहा है",
        to: "से",
        results: "परिणाम",
        noResults: "कोई परिणाम नहीं मिला",
        loadingData: "डेटा लोड हो रहा है...",
        pleaseWait: "कृपया प्रतीक्षा करें...",
        processing: "प्रोसेसिंग...",
        updating: "अपडेट हो रहा है...",
        saving: "सेव हो रहा है...",
        deleting: "हटाया जा रहा है...",
        errorOccurred: "एक त्रुटि हुई",
        tryAgain: "कृपया पुनः प्रयास करें",
        connectionError: "कनेक्शन त्रुटि",
        sessionExpired: "सत्र समाप्त हो गया",
        pleaseLogin: "कृपया फिर से लॉगिन करें",
        unauthorized: "अनधिकृत पहुंच",
        forbidden: "पहुंच निषिद्ध",
        notFound: "पृष्ठ नहीं मिला",
        serverError: "सर्वर त्रुटि",
        maintenance: "सिस्टम रखरखाव",
        comingSoon: "जल्द ही आ रहा है",
        underDevelopment: "विकास के अंतर्गत",
        beta: "बीटा",
        version: "संस्करण",
        help: "मदद",
        support: "समर्थन",
        feedback: "प्रतिक्रिया",
        contact: "संपर्क",
        about: "के बारे में",
        terms: "नियम और शर्तें",
        privacy: "गोपनीयता",
        cookies: "कुकीज़",
        copyright: "कॉपीराइट",
        allRightsReserved: "सर्वाधिकार सुरक्षित",
        poweredBy: "द्वारा संचालित",
        developedBy: "द्वारा विकसित",
        designedBy: "द्वारा डिज़ाइन",
        credits: "क्रेडिट्स",
        license: "लाइसेंस",
        documentation: "प्रलेखन",
        api: "एपीआई",
        changelog: "परिवर्तन लॉग",
        roadmap: "रोडमैप",
        features: "विशेषताएं",
        pricing: "मूल्य निर्धारण",
        plans: "योजनाएं",
        subscribe: "सदस्यता लें",
        unsubscribe: "सदस्यता रद्द करें",
        upgrade: "अपग्रेड",
        downgrade: "डाउनग्रेड",
        trial: "ट्रायल",
        free: "मुफ्त",
        paid: "भुगतान किया गया",
        premium: "प्रीमियम",
        basic: "बेसिक",
        standard: "स्टैंडर्ड",
        professional: "प्रोफेशनल",
        enterprise: "एंटरप्राइज",
        custom: "कस्टम",
        monthly: "मासिक",
        yearly: "वार्षिक",
        lifetime: "आजीवन",
        oneTime: "एक बार",
        recurring: "आवर्ती",
        automatic: "स्वचालित",
        manual: "मैनुअल",
        enabled: "सक्षम",
        disabled: "अक्षम",
        active: "सक्रिय",
        inactive: "निष्क्रिय",
        pending: "लंबित",
        completed: "पूर्ण",
        failed: "विफल",
        cancelled: "रद्द",
        expired: "समाप्त",
        valid: "मान्य",
        invalid: "अमान्य",
        required: "आवश्यक",
        optional: "वैकल्पिक",
        recommended: "अनुशंसित",
        notRecommended: "अनुशंसित नहीं",
        maximum: "अधिकतम",
        minimum: "न्यूनतम",
        average: "औसत",
        total: "कुल",
        count: "गिनती",
        sum: "योग",
        percentage: "प्रतिशत",
        ratio: "अनुपात",
        rate: "दर",
        speed: "गति",
        time: "समय",
        date: "तारीख",
        duration: "अवधि",
        frequency: "आवृत्ति",
        interval: "अंतराल",
        period: "अवधि",
        range: "रेंज",
        limit: "सीमा",
        threshold: "थ्रेशोल्ड",
        target: "लक्ष्य",
        goal: "उद्देश्य",
        objective: "उद्देश्य",
        milestone: "माइलस्टोन",
        deadline: "अंतिम तिथि",
        schedule: "अनुसूची",
        calendar: "कैलेंडर",
        agenda: "एजेंडा",
        reminder: "अनुस्मारक",
        notification: "अधिसूचना",
        alert: "अलर्ट",
        warning: "चेतावनी",
        error: "त्रुटि",
        success: "सफल",
        info: "जानकारी",
        message: "संदेश",
        comment: "टिप्पणी",
        note: "नोट",
        description: "विवरण",
        details: "विवरण",
        summary: "सारांश",
        overview: "अवलोकन",
        preview: "पूर्वावलोकन",
        review: "समीक्षा",
        report: "रिपोर्ट",
        analysis: "विश्लेषण",
        statistics: "सांख्यिकी",
        metrics: "मेट्रिक्स",
        data: "डेटा",
        information: "जानकारी",
        knowledge: "ज्ञान",
        wisdom: "बुद्धिमत्ता",
        insight: "अंतर्दृष्टि",
        perspective: "परिप्रेक्ष्य",
        view: "दृश्य",
        perspective: "परिप्रेक्ष्य",
        angle: "कोण",
        aspect: "पहलू",
        dimension: "आयाम",
        factor: "कारक",
        element: "तत्व",
        component: "घटक",
        part: "भाग",
        piece: "टुकड़ा",
        unit: "इकाई",
        item: "आइटम",
        object: "वस्तु",
        subject: "विषय",
        topic: "विषय",
        theme: "थीम",
        category: "श्रेणी",
        type: "प्रकार",
        kind: "प्रकार",
        sort: "क्रमबद्ध करें",
        order: "क्रम",
        group: "समूह",
        set: "सेट",
        collection: "संग्रह",
        list: "सूची",
        array: "ऐरे",
        table: "टेबल",
        chart: "चार्ट",
        graph: "ग्राफ",
        diagram: "डायग्राम",
        map: "मानचित्र",
        plan: "योजना",
        layout: "लेआउट",
        design: "डिज़ाइन",
        structure: "संरचना",
        format: "प्रारूप",
        style: "शैली",
        theme: "थीम",
        color: "रंग",
        size: "आकार",
        shape: "आकार",
        form: "फॉर्म",
        pattern: "पैटर्न",
        texture: "टेक्सचर",
        material: "सामग्री",
        quality: "गुणवत्ता",
        grade: "ग्रेड",
        level: "स्तर",
        rank: "रैंक",
        status: "स्थिति",
        state: "अवस्था",
        condition: "स्थिति",
        situation: "परिस्थिति",
        context: "संदर्भ",
        environment: "पर्यावरण",
        setting: "सेटिंग",
        background: "पृष्ठभूमि",
        foreground: "अग्रभूमि",
        surface: "सतह",
        depth: "गहराई",
        height: "ऊंचाई",
        width: "चौड़ाई",
        length: "लंबाई",
        area: "क्षेत्र",
        volume: "आयतन",
        weight: "वजन",
        mass: "द्रव्यमान",
        density: "घनत्व",
        pressure: "दबाव",
        temperature: "तापमान",
        humidity: "आर्द्रता",
        light: "प्रकाश",
        sound: "ध्वनि",
        energy: "ऊर्जा",
        power: "शक्ति",
        force: "बल",
        motion: "गति",
        speed: "गति",
        velocity: "वेग",
        acceleration: "त्वरण",
        direction: "दिशा",
        position: "स्थिति",
        location: "स्थान",
        place: "स्थान",
        space: "अंतरिक्ष",
        time: "समय",
        date: "तारीख",
        day: "दिन",
        week: "सप्ताह",
        month: "माह",
        year: "वर्ष",
        century: "शताब्दी",
        era: "युग",
        period: "अवधि",
        age: "आयु",
        generation: "पीढ़ी",
        lifetime: "जीवनकाल",
        duration: "अवधि",
        interval: "अंतराल",
        frequency: "आवृत्ति",
        rate: "दर",
        speed: "गति",
        pace: "गति",
        rhythm: "ताल",
        cycle: "चक्र",
        rotation: "घूर्णन",
        revolution: "परिक्रमण",
        orbit: "कक्षा",
        path: "पथ",
        route: "मार्ग",
        way: "रास्ता",
        direction: "दिशा",
        course: "पाठ्यक्रम",
        track: "ट्रैक",
        trail: "ट्रेल",
        line: "रेखा",
        curve: "वक्र",
        angle: "कोण",
        degree: "डिग्री",
        radian: "रेडियन",
        gradient: "ग्रेडिएंट",
        slope: "ढलान",
        incline: "ढलान",
        decline: "गिरावट",
        rise: "वृद्धि",
        fall: "गिरावट",
        increase: "वृद्धि",
        decrease: "कमी",
        growth: "वृद्धि",
        decline: "गिरावट",
        progress: "प्रगति",
        regress: "प्रतिगमन",
        advance: "अग्रिम",
        retreat: "पीछे हटना",
        forward: "आगे",
        backward: "पीछे",
        up: "ऊपर",
        down: "नीचे",
        left: "बाएं",
        right: "दाएं",
        north: "उत्तर",
        south: "दक्षिण",
        east: "पूर्व",
        west: "पश्चिम",
        top: "शीर्ष",
        bottom: "तल",
        front: "सामने",
        back: "पीछे",
        side: "पक्ष",
        edge: "किनारा",
        corner: "कोना",
        center: "केंद्र",
        middle: "मध्य",
        half: "आधा",
        quarter: "चौथाई",
        third: "तीसरा",
        fourth: "चौथा",
        fifth: "पांचवां",
        sixth: "छठा",
        seventh: "सातवां",
        eighth: "आठवां",
        ninth: "नौवां",
        tenth: "दसवां",
        hundredth: "सौवां",
        thousandth: "हज़ारवां",
        millionth: "दस लाखवां",
        billionth: "अरबवां",
        trillionth: "खरबवां",
        zero: "शून्य",
        one: "एक",
        two: "दो",
        three: "तीन",
        four: "चार",
        five: "पांच",
        six: "छह",
        seven: "सात",
        eight: "आठ",
        nine: "नौ",
        ten: "दस",
        eleven: "ग्यारह",
        twelve: "बारह",
        thirteen: "तेरह",
        fourteen: "चौदह",
        fifteen: "पंद्रह",
        sixteen: "सोलह",
        seventeen: "सत्रह",
        eighteen: "अठारह",
        nineteen: "उन्नीस",
        twenty: "बीस",
        thirty: "तीस",
        forty: "चालीस",
        fifty: "पचास",
        sixty: "साठ",
        seventy: "सत्तर",
        eighty: "अस्सी",
        ninety: "नब्बे",
        hundred: "सौ",
        thousand: "हज़ार",
        million: "दस लाख",
        billion: "अरब",
        trillion: "खरब",
        quadrillion: "पद्म",
        quintillion: "शंख",
        sextillion: "महाशंख",
        septillion: "वृंद",
        octillion: "महावृंद",
        nonillion: "पद्म",
        decillion: "शंख",
        undecillion: "महाशंख",
        duodecillion: "वृंद",
        tredecillion: "महावृंद",
        quattuordecillion: "पद्म",
        quindecillion: "शंख",
        sexdecillion: "महाशंख",
        septendecillion: "वृंद",
        octodecillion: "महावृंद",
        novemdecillion: "पद्म",
        vigintillion: "शंख"
    }
};

// Language management functions
function getLanguage() {
    return localStorage.getItem('language') || 'en';
}

function setLanguage(lang) {
    localStorage.setItem('language', lang);
    document.documentElement.setAttribute('lang', lang);
    updateTextContent();
}

function getTranslation(key) {
    const lang = getLanguage();
    return translations[lang][key] || translations['en'][key] || key;
}

function updateTextContent() {
    const lang = getLanguage();
    const elements = document.querySelectorAll('[data-translate]');
    
    elements.forEach(element => {
        const key = element.getAttribute('data-translate');
        if (key) {
            const translation = getTranslation(key);
            if (element.tagName === 'INPUT' && element.type === 'placeholder') {
                element.placeholder = translation;
            } else {
                element.textContent = translation;
            }
        }
    });
}

// Export functions
window.getLanguage = getLanguage;
window.setLanguage = setLanguage;
window.getTranslation = getTranslation;
window.updateTextContent = updateTextContent; 